### ISSUE TITLE
Question about your Udemy React course

### ISSUE THREAD

**Issue by dluigi** [themaximehardy/the-complete-react-guide#2]
Hey, I found your Udemy course for React
https://www.udemy.com/course/react-the-complete-guide-incl-redux/

Can you please elaborate on the fact that many reviews say the course is too long and not organized properly?

Thanks in advance :)

**Comment by themaximehardy** [comment]
Hi @dluigi,
Thank you for your message. Just to clarify, what I have is not the actual course, but rather my personal notes based on the course. However, I highly recommend purchasing the course itself.
Cheers!
